module.exports = [
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "426714",
            name: "Bakingo",
            uuid: "8b3b3296-5e79-480e-8c1a-852421f69f94",
            city: "10459",
            area: "Greater Noida",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "cixea95z7uleulhhgnbf",
            cuisines: ["Bakery"],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 34,
            minDeliveryTime: 34,
            maxDeliveryTime: 34,
            slaString: "34 MINS",
            lastMileTravel: 6,
            slugs: {
                restaurant: "bakingo-greater-noida-greater-noida",
                city: "noida-1",
            },
            cityState: "10459",
            address:
                "Shop No. 47 First Floor KB Complex Alpha II Greater Noida Uttar Pradesh",
            locality: "Alpha 2",
            parentId: 3818,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 5700,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 5700,
                message: "",
                title: "Delivery Charge",
                amount: "5700",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=7014064~p=1~eid=00000188-aa20-8bf9-129d-c59f0067016f",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "6 kms",
            hasSurge: false,
            sla: {
                restaurantId: "426714",
                deliveryTime: 34,
                minDeliveryTime: 34,
                maxDeliveryTime: 34,
                lastMileTravel: 6,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.1",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "681374",
            name: "GLOBO Ice Creams Of The World",
            uuid: "71386fb1-513f-4f07-8917-989098601aef",
            city: "10459",
            area: "Greater Noida",
            totalRatingsString: "Too Few Ratings",
            cloudinaryImageId: "6a6aa5b55c2494fe25380dcd71dd54b9",
            cuisines: ["Ice Cream", "Desserts", "Bakery"],
            tags: [],
            costForTwo: 15000,
            costForTwoString: "₹150 FOR TWO",
            deliveryTime: 15,
            minDeliveryTime: 10,
            maxDeliveryTime: 20,
            slaString: "10-20 MINS",
            lastMileTravel: 4,
            slugs: {
                restaurant:
                    "globo-ice-creams-of-the-world-new-gamma-1-greater-noida",
                city: "noida-1",
            },
            cityState: "10459",
            address:
                "G-3, 4 &5, BJ MART, JAGAT FARM, GAMMA 1,GREATER NOIDA, GAUTAM BUDDHA NAGAR,GautamBudh Nagar Tahsil-I, Gautam BuddhaNagar , Uttar Pradesh-201308",
            locality: "Gamma 1",
            parentId: 22303,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 4500,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 4500,
                message: "",
                title: "Delivery Charge",
                amount: "4500",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "4 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "40% OFF",
                subHeader: "UPTO ₹80",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "681374",
                deliveryTime: 15,
                minDeliveryTime: 10,
                maxDeliveryTime: 20,
                lastMileTravel: 4,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "--",
            totalRatings: 0,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "98231",
            name: "Chicken Point Restaurant",
            uuid: "13530219-cf96-4405-8a33-173d7dfa0c56",
            city: "10459",
            area: "Greater Noida",
            totalRatingsString: "5000+ ratings",
            cloudinaryImageId: "yz9ypyq37sekxnzikvb6",
            cuisines: ["North Indian"],
            tags: [],
            costForTwo: 15000,
            costForTwoString: "₹150 FOR TWO",
            deliveryTime: 21,
            minDeliveryTime: 21,
            maxDeliveryTime: 21,
            slaString: "21 MINS",
            lastMileTravel: 3.799999952316284,
            slugs: {
                restaurant:
                    "chicken-point-restaurant-greater-noida-noida-expressway",
                city: "noida-1",
            },
            cityState: "10459",
            address:
                "4, VIDHYARAM MARKET JAGAT FARM, RAJA DHABA WALI GALI GRETER NOIDA GAUTAMBODH NAGAR TAHSIL-I GAUTAM BUDDHA NAGAR UTTAR PRADESH",
            locality: "Gamma 1",
            parentId: 16565,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3900,
                message: "",
                title: "Delivery Charge",
                amount: "3900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "3.7 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "10% OFF",
                subHeader: "ABOVE ₹500",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "98231",
                deliveryTime: 21,
                minDeliveryTime: 21,
                maxDeliveryTime: 21,
                lastMileTravel: 3.799999952316284,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.7",
            totalRatings: 5000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "595300",
            name: "Wow! Momo",
            uuid: "901acf50-3119-4128-a270-612e00e72d93",
            city: "10459",
            area: "Alpha 1",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "90ac3da2963978f866177263fba805a7",
            cuisines: [
                "Tibetan",
                "Healthy Food",
                "Asian",
                "Chinese",
                "Snacks",
                "Continental",
                "Desserts",
                "Beverages",
            ],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 35,
            minDeliveryTime: 35,
            maxDeliveryTime: 35,
            slaString: "35 MINS",
            lastMileTravel: 5,
            slugs: {
                restaurant: "wow-momo-alpha-1-wm-greater-noida",
                city: "noida-1",
            },
            cityState: "10459",
            address:
                "Shop No G-02, Ground Floor, Veera Tower, Alpha 1 Commercial belt, Greater Noida- 201310",
            locality: "Alpha 1",
            parentId: 1776,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 5100,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 5100,
                message: "",
                title: "Delivery Charge",
                amount: "5100",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=7042129~p=4~eid=00000188-aa20-8bf9-129d-c5a00067041c",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "5 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹150 OFF",
                subHeader: "ABOVE ₹499",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "595300",
                deliveryTime: 35,
                minDeliveryTime: 35,
                maxDeliveryTime: 35,
                lastMileTravel: 5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.0",
            totalRatings: 100,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "543038",
            name: "BOX8 - Desi Meals",
            uuid: "b00ea072-f232-4321-a0a4-e95396e7c0a9",
            city: "10459",
            area: "Greater Noida",
            totalRatingsString: "500+ ratings",
            cloudinaryImageId: "2c36db5027b5abe00ccc15bf455ea70b",
            cuisines: ["North Indian", "Biryani", "Thalis", "Home Food"],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 21,
            minDeliveryTime: 16,
            maxDeliveryTime: 26,
            slaString: "16-26 MINS",
            lastMileTravel: 4,
            slugs: {
                restaurant: "box8-desi-meals-jagat-farm-greater-noida",
                city: "noida-1",
            },
            cityState: "10459",
            address:
                "G-3, 4 &5, BJ MART, JAGAT FARM, GAMMA 1,GREATER NOIDA, GAUTAM BUDDHA NAGAR,GautamBudh Nagar Tahsil-I, Gautam BuddhaNagar , Uttar Pradesh-201308",
            locality: "Gamma 1",
            parentId: 10655,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 4500,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 4500,
                message: "",
                title: "Delivery Charge",
                amount: "4500",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "4 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "50% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "543038",
                deliveryTime: 21,
                minDeliveryTime: 16,
                maxDeliveryTime: 26,
                lastMileTravel: 4,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.2",
            totalRatings: 500,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "543043",
            name: "ZAZA Mughal Biryani",
            uuid: "7a0f7e2f-6138-44ce-9dd4-fca958a76cc7",
            city: "10459",
            area: "Greater Noida",
            totalRatingsString: "50+ ratings",
            cloudinaryImageId: "990cd5861ab70e380542b4da9d35d97b",
            cuisines: ["Biryani", "North Indian", "Awadhi"],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 21,
            minDeliveryTime: 16,
            maxDeliveryTime: 26,
            slaString: "16-26 MINS",
            lastMileTravel: 4,
            slugs: {
                restaurant: "zaza-21-spice-biryani-jagat-farm-greater-noida",
                city: "noida-1",
            },
            cityState: "10459",
            address:
                "G-3, 4 &5, BJ MART, JAGAT FARM, GAMMA 1,GREATER NOIDA, GAUTAM BUDDHA NAGAR,GautamBudh Nagar Tahsil-I, Gautam BuddhaNagar , Uttar Pradesh-201308",
            locality: "Gamma 1",
            parentId: 22473,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 4500,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 4500,
                message: "",
                title: "Delivery Charge",
                amount: "4500",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "4 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹150 OFF",
                subHeader: "ABOVE ₹450",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "543043",
                deliveryTime: 21,
                minDeliveryTime: 16,
                maxDeliveryTime: 26,
                lastMileTravel: 4,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.3",
            totalRatings: 50,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "668221",
            name: "Macho Momo",
            uuid: "8535d689-c831-4091-8037-3a4cba4d5a83",
            city: "10459",
            area: "Greater Noida",
            totalRatingsString: "20+ ratings",
            cloudinaryImageId: "9447cd942d1cb48155f29b455faa32c5",
            cuisines: ["Tibetan", "Chinese", "Pan-Asian"],
            tags: [],
            costForTwo: 40000,
            costForTwoString: "₹400 FOR TWO",
            deliveryTime: 31,
            minDeliveryTime: 31,
            maxDeliveryTime: 31,
            slaString: "31 MINS",
            lastMileTravel: 2.9000000953674316,
            slugs: {
                restaurant:
                    "macho-momo-by-crispy-fried-chicken-greater-noida-greater-noida",
                city: "noida-1",
            },
            cityState: "10459",
            address:
                "SHOP NO. 26 F, AMRITPURAM, SHRI AMRIT PLAZA,JAGAT FARM, GAMMA 1, GREATER NOIDA, GAMA-1, GautamBudh Nagar Tahsil-I, Gautam Buddha Nagar , Uttar Pradesh - 201308",
            locality: "Amritpuram",
            parentId: 378120,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=7027155~p=7~eid=00000188-aa20-8bf9-129d-c5a100670716",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.9 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "50% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "668221",
                deliveryTime: 31,
                minDeliveryTime: 31,
                maxDeliveryTime: 31,
                lastMileTravel: 2.9000000953674316,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.2",
            totalRatings: 20,
            new: false,
        },
        subtype: "basic",
    },
];
